name: Metrics
on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          template: repository
          config_padding: 10

          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: X

          plugin_lines: yes

          plugin_introduction: yes
          plugin_introduction_title: yes

          plugin_followup: yes
          plugin_followup_sections: repositories

          plugin_activity: yes
          plugin_activity_timestamps: yes

          plugin_habits: yes
          plugin_languages: yes
          plugin_repositories: yes
